Thing.create(name: "Book")
Thing.create(name: "Apple")
Thing.create(name: "Hamster")
Thing.create(name: "Dinosaur")
Thing.create(name: "Chair")
Thing.create(name: "Palm Tree")
Thing.create(name: "Table")
Thing.create(name: "Lamp")
Thing.create(name: "Car")
Thing.create(name: "Plane")
Thing.create(name: "Train")
Thing.create(name: "Motorcycle")
